= Kenya Here We Go!

I can’t believe that it has been about a month ago when I found out I was accepted to be part of the upcoming Kenya experience with BU School of Public Health and School of Field Studies. I accepted the offer, knowing it is one of those rare opportunities to travel to East Africa, but most importantly doing something meaningful not just for myself, but in the name of public health.

Without a doubt, I want to thank everyone who has followed along the past month — all your likes, comments, and congrats — have made me feel extremely loved.

But, especially today, I want to thank all my friends, mentors, colleagues, and family who have been a huge support in making this experiential learning trip a financial reality.

When I first came up with the idea for a “kickstarter”, I wasn’t sure if it would get off the ground. Usually, I’m don’t like to view ideas pessimistically, but I never imagined that this fundraiser would be as successful. Some might say that it wasn’t a success because I didn’t reach my original goal, but I consider it a great success — both in the tremendous amount of social media publicity, but also financial success.

I am absolutely honored. I can not stress this enough. Sincerely, I thank you.

Special shoutout to: Naeal A., Richard A., Aditi A., Priya C., Xinhua C., Lindsey C., Hilary C., Amal H., Alex D., Dylan L., Sheina G., Michelle F., Kat L., Jenn N., Colin O., Kyle P., Nick R., Varsha S., Michelle S., Emily W., Silong Y., and Banco Santander.

P.S. I hope to use this site as a journal documenting the entire process of getting myself to Kenya. Stay tuned.